### Python Assignment-2: Data Structures, Functions, Numpy & Pandas

### Section A: Data Structures & Control Structures

#### 1.	Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

In [1]:
list = [1,2,3,4,5]
print(list)

[1, 2, 3, 4, 5]

In [2]:
# Append
list.append(6)
list

[1, 2, 3, 4, 5, 6]

In [3]:
# Extend
list.extend([1,14,3,2])
list

[1, 2, 3, 4, 5, 6, 1, 14, 3, 2]

In [4]:
# Insert
list.insert(4,8) # 4-index, 5-value
list

[1, 2, 3, 4, 8, 5, 6, 1, 14, 3, 2]

In [5]:
# Remove
list.remove(2) # removes first matching value 
list

[1, 3, 4, 8, 5, 6, 1, 14, 3, 2]

In [6]:
# Pop
list.pop(3)  # pop the index placed value
list

[1, 3, 4, 5, 6, 1, 14, 3, 2]

In [7]:
# Index
list.index(5) # index value of number in list

3

In [8]:
# Count
list.count(3) #counts the numbers in list

2

In [9]:
# Sort
list.sort() #ascending order
list

[1, 1, 2, 3, 3, 4, 5, 6, 14]

In [10]:
list.sort(reverse=True) # descending order
list

[14, 6, 5, 4, 3, 3, 2, 1, 1]

In [11]:
# Reverse
list.reverse() # reverse the list
list

[1, 1, 2, 3, 3, 4, 5, 6, 14]

In [12]:
# Clear 
list.clear()
list

[]

#### 2.	Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.

In [13]:
tuple = ('javeed','tasin','pavan')
tuple

('javeed', 'tasin', 'pavan')

In [14]:
tuple(1) = 'venki' #error

SyntaxError: cannot assign to function call here. Maybe you meant '==' instead of '='? (3141633666.py, line 1)

Reason:
* Tuples are immutable,we cannnot change elements directly

#### 3.	Create a set of integers with some duplicate values. Print the set and explain the output.

In [15]:
set = {1,2,2,3,4,5,5}
set

{1, 2, 3, 4, 5}

* sets cannot allow duplicates, it can remove duplicates automatically

#### 4.	Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.

In [16]:
dict = {
    'name' : 'javeed',
    'age' : 22,
    'city' : 'Madanapalli'
}
dict

{'name': 'javeed', 'age': 22, 'city': 'Madanapalli'}

In [17]:
# update the age
dict['age'] = 20
dict

{'name': 'javeed', 'age': 20, 'city': 'Madanapalli'}

In [18]:
# add new key
dict['email'] = 'javeedbasha1019@gmail.com'
dict

{'name': 'javeed',
 'age': 20,
 'city': 'Madanapalli',
 'email': 'javeedbasha1019@gmail.com'}

In [19]:
#final dictionary
dict

{'name': 'javeed',
 'age': 20,
 'city': 'Madanapalli',
 'email': 'javeedbasha1019@gmail.com'}

#### 5.	 Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

In [21]:
age = int(input('Enter the age : '))
if age >= 18:
    print('Eligible to vote')
else:
    print('Not eligible to vote')

Enter the age :  22

Eligible to vote

#### 6.	Given a 'marks' variable, print the grade:
- 90 and above: 'A'
- 75–89: 'B'
- 50–74: 'C'
- Below 50: 'Fail'

In [22]:
marks = int(input('Enter your marks : '))
if marks >= 90 :
    print('Grade-A')
elif marks >= 75:
        print('Grade-B')
elif marks >= 50:
    print('Grade-C')
elif marks < 50:
    print('Fail')

Enter your marks :  75

Grade-B

#### 7.	Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [24]:
num = int(input('Give a number : '))
if num >0 :
    print(f'{num} is Positive')
    if num% 2 == 0:
        print(f'{num} is Even')
elif num  == 0 :
    print(f'{num} is Zero')
else:
    print(f'{num} is Negative')

Give a number :  56

56 is Positive
56 is Even

### Section B: Numpy

#### 8.	Create:
- A scalar using np.array(5)
- A 1D array with values 1 to 5
- A 2D array (2x3) with values from 10 to 60 in steps of 10

In [25]:
import numpy as np

In [26]:
scalar = np.array(5)
scalar

array(5)

In [27]:
# 1D array
d1_array = np.array([1,2,3,4,5])
d1_array

array([1, 2, 3, 4, 5])

In [28]:
# 2D array
d2_array = np.array([[1,2,3],[4,5,6]])
d2_array

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
d2_array = np.arange(10,70,10).reshape(2,3)  #A 2D array (2x3) with values from 10 to 60 in steps of 10
d2_array

array([[10, 20, 30],
       [40, 50, 60]])

#### 9.	Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [30]:
d4_array = np.random.randint(0,101, size=(4,4))
print(d4_array)

[[18 96 39 77]
 [99 52 47 46]
 [73 38 10 76]
 [44 49 47  1]]

#### 10.	Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [31]:
import pandas as pd
import numpy as np

d_array = np.random.randint(0,100, size=(3,3))
d_array

array([[ 3, 91, 70],
       [77, 43, 35],
       [10, 65, 92]], dtype=int32)

In [32]:
df = pd.DataFrame(d_array, columns=['A','B','C'])
df

    A   B   C
0   3  91  70
1  77  43  35
2  10  65  92

### Section C: Exploring Pandas
#### 11.	Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
- Use .info(), .describe()
- Select 'Name' and 'City' columns
- Drop 'City' column
- Fill any missing values in 'Salary' column with the mean
- Remove any duplicate rows

In [40]:
import pandas as pd
import numpy as np


data = {
    'Name' : ['Javeed','Tasin','Pavan','venki','Charan',
              'Madhan','Jabeer','Somu','Yashwanth','Saleem'],
    'Age' : [22,21,23,43,54,
             23,24,30,32,19],
    'City' : ['goa','pune','delhi','guntur','chennai',
              'hyd','bglr','gujarat','kerala','pune'],
    'Salary' : [50000, 40000, 60000, np.nan, 80000,
               30000, 25000, 70000, np.nan, 50000]
}
df = pd.DataFrame(data)
df

        Name  Age     City   Salary
0     Javeed   22      goa  50000.0
1      Tasin   21     pune  40000.0
2      Pavan   23    delhi  60000.0
3      venki   43   guntur      NaN
4     Charan   54  chennai  80000.0
5     Madhan   23      hyd  30000.0
6     Jabeer   24     bglr  25000.0
7       Somu   30  gujarat  70000.0
8  Yashwanth   32   kerala      NaN
9     Saleem   19     pune  50000.0

#### Use .info(), .describe()

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    10 non-null     object
 1   Age     10 non-null     int64
 2   City    10 non-null     object
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes

In [42]:
df.describe()

            Age        Salary
count  10.00000      8.000000
mean   29.10000  50625.000000
std    11.25907  18980.723304
min    19.00000  25000.000000
25%    22.25000  37500.000000
50%    23.50000  50000.000000
75%    31.50000  62500.000000
max    54.00000  80000.000000

In [43]:
df.isna().sum()

Name      0
Age       0
City      0
Salary    2
dtype: int64

#### Select 'Name' and 'City' columns

In [44]:
df[['Name','City']]

        Name     City
0     Javeed      goa
1      Tasin     pune
2      Pavan    delhi
3      venki   guntur
4     Charan  chennai
5     Madhan      hyd
6     Jabeer     bglr
7       Somu  gujarat
8  Yashwanth   kerala
9     Saleem     pune

#### Drop 'City' column

In [45]:
df.drop('City', axis=1, inplace=True)
df

        Name  Age   Salary
0     Javeed   22  50000.0
1      Tasin   21  40000.0
2      Pavan   23  60000.0
3      venki   43      NaN
4     Charan   54  80000.0
5     Madhan   23  30000.0
6     Jabeer   24  25000.0
7       Somu   30  70000.0
8  Yashwanth   32      NaN
9     Saleem   19  50000.0

#### Fill any missing values in 'Salary' column with the mean

In [46]:
df['Salary'] = df['Salary'].fillna(df['Salary'].mean())
df

        Name  Age   Salary
0     Javeed   22  50000.0
1      Tasin   21  40000.0
2      Pavan   23  60000.0
3      venki   43  50625.0
4     Charan   54  80000.0
5     Madhan   23  30000.0
6     Jabeer   24  25000.0
7       Somu   30  70000.0
8  Yashwanth   32  50625.0
9     Saleem   19  50000.0

#### Remove any duplicate rows

In [47]:
df.drop_duplicates(subset=['Salary'], inplace=True)
df

     Name  Age   Salary
0  Javeed   22  50000.0
1   Tasin   21  40000.0
2   Pavan   23  60000.0
3   venki   43  50625.0
4  Charan   54  80000.0
5  Madhan   23  30000.0
6  Jabeer   24  25000.0
7    Somu   30  70000.0