### Python Assignments-4: BASIC STATISTICS-2

Problem Statement : Hospital Patient Data Analysis
Context:
A hospital maintains patient records including admission details, department, diagnosis, doctor, and bill amount. You have two datasets: one with patient info and another with billing details. Some patients have blank bill amounts, and there are multiple rows for the same patient due to follow-ups.
Tasks:
1.	Load the patient dataset and show summary with info().
2.	Select only the columns relevant for billing: ['PatientID', 'Department', 'Doctor', 'BillAmount'].
3.	Drop administrative columns like ['ReceptionistID', 'CheckInTime'].
4.	Use groupby to find total bill amount per department.
5.	Remove duplicate patient records based on PatientID.
6.	Fill missing BillAmount values with the mean bill amount.
7.	Merge the billing dataset with patient dataset on PatientID.
8.	Concatenate an additional DataFrame that contains new patients for the current week (row-wise).
9.	Concatenate new billing category columns like ['InsuranceCovered', 'FinalAmount'] (column-wise).

In [30]:
import pandas as pd

#### 1. Load the patient dataset and show summary with info()

In [31]:
patients_df = pd.read_csv(r"Data\Patient_Data.csv")
patients_df.head()

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime
0,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00
1,102,Bob,Neurology,Dr. John,NaN,2,2023-01-11 10:30
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,1,2023-01-12 11:00
3,104,David,Cardiology,Dr. Smith,6200.0,3,2023-01-13 12:00
4,105,Eva,Dermatology,Dr. Rose,NaN,2,2023-01-14 08:45

In [32]:
billing_df = pd.read_csv('Billing_Data.csv')
billing_df.head()

   PatientID  InsuranceCovered  FinalAmount
0        101              2000         3000
1        102              1500         3500
2        103              2500         5000
3        104              3000         3200
4        105              1000         4000

In [33]:
patients_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PatientID       6 non-null      int64
 1   Name            6 non-null      object
 2   Department      6 non-null      object
 3   Doctor          6 non-null      object
 4   BillAmount      4 non-null      float64
 5   ReceptionistID  6 non-null      int64
 6   CheckInTime     6 non-null      object
dtypes: float64(1), int64(2), object(4)
memory usage: 468.0+ bytes

In [34]:
patients_df.describe()

        PatientID   BillAmount  ReceptionistID
count    6.000000     4.000000        6.000000
mean   102.666667  5925.000000        1.666667
std      1.632993  1192.686044        0.816497
min    101.000000  5000.000000        1.000000
25%    101.250000  5000.000000        1.000000
50%    102.500000  5600.000000        1.500000
75%    103.750000  6525.000000        2.000000
max    105.000000  7500.000000        3.000000

#### 2.	Select only the columns relevant for billing: ['PatientID', 'Department', 'Doctor', 'BillAmount'].

In [35]:
billing_columns = ['PatientID','Department', 'Doctor', 'BillAmount']
patients_billing_df = patients_df[billing_columns]
patients_billing_df.head()

   PatientID   Department     Doctor  BillAmount
0        101   Cardiology  Dr. Smith      5000.0
1        102    Neurology   Dr. John         NaN
2        103  Orthopedics    Dr. Lee      7500.0
3        104   Cardiology  Dr. Smith      6200.0
4        105  Dermatology   Dr. Rose         NaN

#### 3. Drop administrative columns like ['ReceptionistID', 'CheckInTime'].

In [36]:
patients_df = patients_df.drop(columns=['ReceptionistID', 'CheckInTime'])
patients_df

   PatientID     Name   Department     Doctor  BillAmount
0        101    Alice   Cardiology  Dr. Smith      5000.0
1        102      Bob    Neurology   Dr. John         NaN
2        103  Charlie  Orthopedics    Dr. Lee      7500.0
3        104    David   Cardiology  Dr. Smith      6200.0
4        105      Eva  Dermatology   Dr. Rose         NaN
5        101    Alice   Cardiology  Dr. Smith      5000.0

#### 4.	Use groupby to find total bill amount per department.

In [37]:
patients_df.groupby('Department')['BillAmount'].sum().reset_index()

    Department  BillAmount
0   Cardiology     16200.0
1  Dermatology         0.0
2    Neurology         0.0
3  Orthopedics      7500.0

#### 5.	Remove duplicate patient records based on PatientID.

In [38]:
patients_df = patients_df.drop_duplicates(subset='PatientID')
patients_df

   PatientID     Name   Department     Doctor  BillAmount
0        101    Alice   Cardiology  Dr. Smith      5000.0
1        102      Bob    Neurology   Dr. John         NaN
2        103  Charlie  Orthopedics    Dr. Lee      7500.0
3        104    David   Cardiology  Dr. Smith      6200.0
4        105      Eva  Dermatology   Dr. Rose         NaN

#### 6.	Fill missing BillAmount values with the mean bill amount.

In [39]:
mean = patients_df['BillAmount'].mean()
mean

np.float64(6233.333333333333)

In [40]:
patients_df.loc[:,'BillAmount'] = patients_df[['BillAmount']].fillna(mean)
patients_df['BillAmount'].isnull().sum()

np.int64(0)

In [41]:
patients_df

   PatientID     Name   Department     Doctor   BillAmount
0        101    Alice   Cardiology  Dr. Smith  5000.000000
1        102      Bob    Neurology   Dr. John  6233.333333
2        103  Charlie  Orthopedics    Dr. Lee  7500.000000
3        104    David   Cardiology  Dr. Smith  6200.000000
4        105      Eva  Dermatology   Dr. Rose  6233.333333

#### 7.	Merge the billing dataset with patient dataset on PatientID.

In [42]:
merge_df = pd.merge(patients_df,billing_df,  on= 'PatientID')
merge_df.head()

,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.000000,2000,3000
1,102,Bob,Neurology,Dr. John,6233.333333,1500,3500
2,103,Charlie,Orthopedics,Dr. Lee,7500.000000,2500,5000
3,104,David,Cardiology,Dr. Smith,6200.000000,3000,3200
4,105,Eva,Dermatology,Dr. Rose,6233.333333,1000,4000

#### 8.	Concatenate an additional DataFrame that contains new patients for the current week (row-wise).

In [43]:
new_patients = pd.DataFrame({
    'PatientID':[106,107],
    'Name':['Frank','Grace'],
    'Department':['Neurology','Cardiology'],
    'Doctor':['Dr. John','Dr. Smith'],
    'BillAmount':[6800,7200]
})

In [44]:
combined_df = pd.concat([patients_df, new_patients], axis=0).reset_index(drop=True)   # billing data 
combined_df

   PatientID     Name   Department     Doctor   BillAmount
0        101    Alice   Cardiology  Dr. Smith  5000.000000
1        102      Bob    Neurology   Dr. John  6233.333333
2        103  Charlie  Orthopedics    Dr. Lee  7500.000000
3        104    David   Cardiology  Dr. Smith  6200.000000
4        105      Eva  Dermatology   Dr. Rose  6233.333333
5        106    Frank    Neurology   Dr. John  6800.000000
6        107    Grace   Cardiology  Dr. Smith  7200.000000

#### 9.	Concatenate new billing category columns like ['InsuranceCovered', 'FinalAmount'] (column-wise).

In [45]:
insurance_df = pd.DataFrame({
    'InsuranceCovered':[2000,1500,2500,3000,1000],
    'FinalAmount':[3000,3500,5000,3200,4000]
})

In [46]:
final_df = pd.concat([combined_df, insurance_df], axis=1)
final_df

,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.000000,2000.0,3000.0
1,102,Bob,Neurology,Dr. John,6233.333333,1500.0,3500.0
2,103,Charlie,Orthopedics,Dr. Lee,7500.000000,2500.0,5000.0
3,104,David,Cardiology,Dr. Smith,6200.000000,3000.0,3200.0
4,105,Eva,Dermatology,Dr. Rose,6233.333333,1000.0,4000.0
5,106,Frank,Neurology,Dr. John,6800.000000,NaN,NaN
6,107,Grace,Cardiology,Dr. Smith,7200.000000,NaN,NaN